FROM gliderlabs/alpine:3.3
VOLUME /mnt/routes
EXPOSE 80

ENV GOPATH /go
RUN apk-install go git mercurial
COPY . /go/src/github.com/gliderlabs/logspout
WORKDIR /go/src/github.com/gliderlabs/logspout
RUN GO15VENDOREXPERIMENT=1 go build  -o /bin/logspout 
ENTRYPOINT ["/bin/logspout"]
